@startuml
left to right direction

artifact "mes-tool-mock-ui" {
    component ToolMockUI <<SPA Frontend>>

}

artifact "mes-tool-mock-srv" #E3664A {
    component ToolMockService #FEFECE
    interface REST as rest2 #FEFECE
    ToolMockService -- rest2
}

actor MockUser

queue ToolStatusTopic <<EventTopic>>
queue PartsTopic <<EventTopic>>
queue UptimeTopic <<ValueTopic>>
queue YieldTopic <<ValueTopic>>

artifact "mes-tool-status-srv" {
    component ToolStatusService
}

artifact "mes-tool-product-srv" {
    component ToolProductService
}

artifact "mes-tool-kpi-srv" {
    component ToolKpiService
}

artifact "mes-tool-dashboard-service" {
    component DashboardService

    interface REST as rest3
    DashboardService -- rest3
}

artifact "mes-tool-dashboard-ui" {
    component DashboardUI <<SPA Frontend>>
}

actor MonitoringUser

queue AvailabilityTopic <<ValueTopic>>
queue ActualCycleTimeTopic <<ValueTopic>>
queue TheoreticalCycleTimeTopic <<ValueTopic>>
queue PerformanceEfficiencyTopic <<ValueTopic>>
queue OverallEquipmentEfficiencyTopic <<ValueTopic>>
queue TotalEffectiveEquipmentPerformanceTopic <<ValueTopic>>
queue UtilizationTopic <<ValueTopic>>
queue QualityRateTopic <<ValueTopic>>

MockUser --> ToolMockUI
ToolMockUI --> rest2

ToolMockService --> ToolStatusTopic: publish
ToolMockService --> PartsTopic: publish

ToolProductService --> YieldTopic: publish
PartsTopic --> ToolProductService: subscribe

ToolStatusService --> UptimeTopic: publish
ToolStatusTopic --> ToolStatusService: subscribe

UptimeTopic --> ToolKpiService: subscribe
YieldTopic --> ToolKpiService: subscribe

ToolKpiService --> AvailabilityTopic: publish
ToolKpiService --> ActualCycleTimeTopic: publish
ToolKpiService --> TheoreticalCycleTimeTopic: publish
ToolKpiService --> PerformanceEfficiencyTopic: publish
ToolKpiService --> OverallEquipmentEfficiencyTopic: publish
ToolKpiService --> TotalEffectiveEquipmentPerformanceTopic: publish
ToolKpiService --> UtilizationTopic: publish
ToolKpiService --> QualityRateTopic: publish

AvailabilityTopic --> DashboardService: subscribe
ActualCycleTimeTopic --> DashboardService: subscribe
TheoreticalCycleTimeTopic --> DashboardService: subscribe
PerformanceEfficiencyTopic --> DashboardService: subscribe
OverallEquipmentEfficiencyTopic --> DashboardService: subscribe
TotalEffectiveEquipmentPerformanceTopic --> DashboardService: subscribe
UtilizationTopic --> DashboardService: subscribe
QualityRateTopic --> DashboardService: subscribe

DashboardUI --> rest3
MonitoringUser --> DashboardUI

@enduml