@startuml
left to right direction

artifact "mes-tool-mock-ui" {
    component ToolMockUI <<SPA Frontend>>

}

artifact "mes-tool-mock-srv" {
    component ToolMockServer
    interface REST as rest2
    ToolMockServer -- rest2
}

actor MockUser

queue ToolStatusTopic <<EventTopic>>
queue PartsTopic <<EventTopic>>
queue UptimeTopic <<ValueTopic>>
queue YieldTopic <<ValueTopic>>

artifact "mes-tool-status-srv" {
    component ToolStatusService
}

artifact "mes-tool-product-srv" {
    component ToolProductService
}

artifact "mes-tool-kpi-srv" {
    component ToolKpiService
}

artifact "mes-dashboard-service" {
    component DashboardService

    interface REST as rest3
    DashboardService -- rest3
}

artifact "mes-dashboard-ui" {
    component DashboardUI <<SPA Frontend>>
}

actor MonitoringUser

queue AvailabilityTopic <<ValueTopic>>
queue ActualCycleTimeTopic <<ValueTopic>>
queue TheoreticalCycleTimeTopic <<ValueTopic>>
queue PerformanceEfficiencyTopic <<ValueTopic>>
queue OverallEquipmentEfficiencyTopic <<ValueTopic>>
queue TotalEffectiveEquipmentPerformanceTopic <<ValueTopic>>
queue UtilizationTopic <<ValueTopic>>
queue QualityRateTopic <<ValueTopic>>

MockUser --> ToolMockUI
ToolMockUI --> rest2

ToolMockServer --> ToolStatusTopic: publish
ToolMockServer --> PartsTopic: publish

ToolProductService --> YieldTopic: publish
PartsTopic --> ToolProductService: subscribe

ToolStatusService --> UptimeTopic: publish
ToolStatusTopic --> ToolStatusService: subscribe

UptimeTopic --> ToolKpiService
YieldTopic --> ToolKpiService

ToolKpiService --> AvailabilityTopic: subscribe
ToolKpiService --> ActualCycleTimeTopic: subscribe
ToolKpiService --> TheoreticalCycleTimeTopic: subscribe
ToolKpiService --> PerformanceEfficiencyTopic: subscribe
ToolKpiService --> OverallEquipmentEfficiencyTopic: subscribe
ToolKpiService --> TotalEffectiveEquipmentPerformanceTopic: subscribe
ToolKpiService --> UtilizationTopic: subscribe
ToolKpiService --> QualityRateTopic: subscribe

AvailabilityTopic --> DashboardService: publish
ActualCycleTimeTopic --> DashboardService: publish
TheoreticalCycleTimeTopic --> DashboardService: publish
PerformanceEfficiencyTopic --> DashboardService: publish
OverallEquipmentEfficiencyTopic --> DashboardService: publish
TotalEffectiveEquipmentPerformanceTopic --> DashboardService: publish
UtilizationTopic --> DashboardService: publish
QualityRateTopic --> DashboardService: publish

DashboardUI --> rest3
MonitoringUser --> DashboardUI

@enduml