@startuml
'https://plantuml.com/state-diagram
skinparam defaultTextAlignment left
scale 350 width

[*] --> UP
state DOWN : entry/ issue ToolDownEvent

state UP {
    state UP: entry/ ToolUpEventAction, ToolUpEvent(tool)
    state UP: PART_LOADING / LoadPartAction, PartLoadedEvt(tool, part)
    state UP: PART_UNLOADING / UnloadPartAction, PartUnloadedEvt(tool, part)

    state STOPPED
    STOPPED: entry / ToolStoppedEvent(tool)

    [*] --> STOPPED
    STOPPED --> OPERATING: START [FlowFree]
    STOPPED --> IDLE: START [FlowNotFree]

    OPERATING --> STOPPED: STOP
    OPERATING --> IDLE

    state IDLE {
        IDLE: entry / ToolIdleEvent(tool)
        state UPSTREAM: entry / ToolIdleEvent(UPSTREAM)
        state DOWNSTREAM: entry: ToolIdleEvent(DOWNSTREAM)
        state CHOICE_IDLE <<choice>>
        [*] --> UPSTREAM: [InportEmpty]

        CHOICE_IDLE --> DOWNSTREAM: [OutportFull]
    }

    state OPERATING {
        OPERATING: entry / ToolOperatingEvent(tool)
        state LOADING_PROCESS: entry / ProcessNewPartAction, PartInProcessEvent(tool, part)
        state UNLOADING_PROCESS: entry / EjectFinishedPartAction, PartProcessedEvent(tool, part)
        state CHOICE_LOADING <<choice>>
        state PROCESSING_PART

        [*] --> CHOICE_LOADING
        CHOICE_LOADING --> LOADING_PROCESS: [ProcessEmpty]
        CHOICE_LOADING --> UNLOADING_PROCESS: [ProcessNotEmpty]
        LOADING_PROCESS --> PROCESSING_PART

        PROCESSING_PART --> UNLOADING_PROCESS: [await cycle time]
        UNLOADING_PROCESS --> LOADING_PROCESS: [FlowIsFree]
        UNLOADING_PROCESS --> [*] : [InportEmpty]
        UNLOADING_PROCESS --> [*] : [OutportFull]
    }

    IDLE --> OPERATING: [FlowIsFree]
    IDLE --> STOPPED: STOP
}

UP --> DOWN: FAULT
DOWN --> UP: FAULT_CLEAR
@enduml