@startuml
'https://plantuml.com/state-diagram
skinparam defaultTextAlignment left
scale 350 width

[*] --> UP
state DOWN : entry/ issue ToolDownEvent

state UP {
    state UP: entry/ ToolUpEventAction, ToolUpEvent(tool)
    state UP: PART_LOADING / LoadPartAction, PartLoadedEvt(tool, part)
    state UP: PART_UNLOADING / UnloadPartAction, PartUnloadedEvt(tool, part)

    state STOPPED
    STOPPED: entry / ToolStoppedEvent(tool)
    state IDLE {
        state UPSTREAM: entry / ToolIdleEvent(UPSTREAM)
        state DOWNSTREAM: entry: ToolIdleEvent(DOWNSTREAM)
        state c <<choice>>
        [*] --> c
        c --> UPSTREAM: [InportEmpty]
        c --> DOWNSTREAM: [OutportFull]
    }

    state OPERATING {
        state PROCESSING_PART
        state LOADING_PROCESS: entry / ProcessNewPartAction, PartInProcessEvent(tool, part)
        state UNLOADING_PROCESS: entry / EjectFinishedPartAction, PartProcessedEvent(tool, part), FINISHED
        state c1 <<choice>>

        [*] --> c1
        c1 --> LOADING_PROCESS: [ProcessEmpty]
        c1 --> UNLOADING_PROCESS: [ProcessNotEmpty]
        LOADING_PROCESS --> PROCESSING_PART

        PROCESSING_PART --> UNLOADING_PROCESS: [await cycle time]
        UNLOADING_PROCESS --> LOADING_PROCESS: [FlowIsFree]

    }

    state c2 <<choice>>

    [*] --> STOPPED
    STOPPED --> IDLE: START
    OPERATING: START [FlowIsFree]

    OPERATING --> STOPPED: STOP
    OPERATING --> IDLE: FINISHED


    IDLE --> OPERATING: [FlowIsFree]
    IDLE --> STOPPED: STOP
}

UP --> DOWN: FAULT
DOWN --> UP: FAULT_CLEAR
@enduml