@startuml
'https://plantuml.com/state-diagram
skinparam defaultTextAlignment left
scale 350 width

[*] --> UP
state DOWN : entry/ issue ToolDownEvent

state UP {
    state UP: entry/ ToolUpEventAction, ToolUpEvent(tool)
    state UP: PART_LOADING / LoadPartAction, PartLoadedEvt(tool, part)
    state UP: PART_UNLOADING / UnloadPartAction, PartUnloadedEvt(tool, part)

    state STOPPED
    STOPPED: entry / ToolStoppedEvent(tool)

    state CHOICE_START <<choice>>
    [*] --> STOPPED
    STOPPED --> CHOICE_START: START
    CHOICE_START --> OPERATING: [ InportNotEmpty\n&&\nOutportNotFull ]
    CHOICE_START --> IDLE: [ InportEmpty \n ||\n OutportFull ]

    OPERATING --> STOPPED: STOP
    OPERATING --> IDLE

    state IDLE {
        state CHOICE1 <<choice>>
        state BLOCKED_UPSTREAM: entry / ToolIdleEvent(UPSTREAM)
        state BLOCKED_DOWNSTREAM: entry / ToolIdleEvent(DOWNSTREAM)
        [*] --> CHOICE1
        CHOICE1 --> BLOCKED_UPSTREAM: [ InportEmpty ]
        CHOICE1 --> BLOCKED_DOWNSTREAM: [ OutportFull ]
        BLOCKED_DOWNSTREAM --> BLOCKED_UP_AND_DOWNSTREAM: [ InportEmpty ] /\n ToolIdleEvent(UPSTREAM) ]
        BLOCKED_UPSTREAM --> BLOCKED_UP_AND_DOWNSTREAM: [ OutportFull ] /\n ToolIdleEvent(DOWNSTREAM) ]
        BLOCKED_UP_AND_DOWNSTREAM --> BLOCKED_UPSTREAM: [ OutportNotFull ]
        BLOCKED_UP_AND_DOWNSTREAM --> BLOCKED_DOWNSTREAM: [ InportNotEmpty ]
        BLOCKED_DOWNSTREAM --> [*]: [ OutportNotFull ]
        BLOCKED_UPSTREAM --> [*]: [ InputNotEmpty ]
     }

    state OPERATING {
        OPERATING: entry / ToolOperatingEvent(tool)
                state LOADING_PROCESS: PartInProcessEvent(tool, part)
                state UNLOADING_PROCESS: PartProcessedEvent(tool, part)
                state CHOICE_LOADING <<choice>>
                state CHOICE_UNLOADING <<choice>>
                state PROCESSING_PART

                [*] --> CHOICE_LOADING
                CHOICE_LOADING --> LOADING_PROCESS: [ProcessEmpty]
                CHOICE_LOADING --> UNLOADING_PROCESS: [ProcessNotEmpty]
                LOADING_PROCESS --> PROCESSING_PART

                PROCESSING_PART --> UNLOADING_PROCESS: [await process time]
                UNLOADING_PROCESS --> CHOICE_UNLOADING: [await unloading time]
                CHOICE_UNLOADING --> LOADING_PROCESS: [ InportNotEmpty \n&& \nOutportNotFull ]
                CHOICE_UNLOADING --> [*] : [ InportEmpty || OutportFull ]
    }



    IDLE --> OPERATING
    IDLE --> STOPPED: STOP

}

UP --> DOWN: FAULT
DOWN --> UP: FAULT_CLEAR
@enduml