@startuml
'https://plantuml.com/state-diagram
skinparam defaultTextAlignment left
scale 350 width

[*] --> UP
state DOWN : entry/ issue ToolDownEvent

state UP {
    state UP: entry/ ToolUpEventAction, ToolUpEvent(tool)
    state UP: PART_LOADING / LoadPartAction, PartLoadedEvt(tool, part)
    state UP: PART_UNLOADING / UnloadPartAction, PartUnloadedEvt(tool, part)

    state STOPPED
    STOPPED: entry / ToolStoppedEvent(tool)
    state IDLE
    state PROCESSING {
        state PROCESSING_PART
        state LOADING_PROCESS
        state LOADING_PROCESS: entry/ ProcessNewPartAction, PartInProcessEvent(tool, part)

        state UNLOADING_PROCESS

        [*] --> PROCESSING_PART
        PROCESSING_PART --> LOADING_PROCESS: [ProcessEmpty]
        LOADING_PROCESS --> PROCESSING_PART

        PROCESSING_PART --> UNLOADING_PROCESS: [await cycle time] / \nEjectFinishedPartAction, \nPartProcessedEvent(tool, part), \nFINISHED
        UNLOADING_PROCESS --> LOADING_PROCESS: [FlowIsFree]

    }

    [*] --> STOPPED
    STOPPED --> PROCESSING: START [FlowIsFree]
    STOPPED --> IDLE: START [InportEmpty] / \nToolIdleEvt(tool, UPSTREAM)
    STOPPED --> IDLE: START [OutportFull] / \nToolIdleEvt(tool, DOWNSTREAM)
    PROCESSING --> STOPPED: STOP
    PROCESSING --> IDLE: FINISHED: \n[InportEmpty] / \nToolIdleEvent(UPSTREAM)
    PROCESSING --> IDLE: FINISHED: \n[OutportFull] / \nToolIdleEvent(DOWNSTREAM)

    IDLE --> PROCESSING: [FlowIsFree]
    IDLE --> STOPPED: STOP
}

UP --> DOWN: FAULT
DOWN --> UP: FAULT_CLEAR
@enduml