@startuml
'https://plantuml.com/state-diagram

state A {
    state B
    state C
    state c <<choice>>


    [*] --> B
    B --> c: EVT1
    c --> A1: [guard2]
    c --> C: [guard1]


    state A1 {
       state d <<choice>>
       state C1
       [*] --> d
       d --> C1: [guard3]
       d --> D1: [guard4]
    }
}
@enduml